application: bojangles
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /_ah/spi/.*
  script: api.app

- url: /.*
  script: main.app

libraries:
 - name: endpoints
   version: latest